# Model and Save
MODEL_PATH=""
MODEL_NAME=""
LOG_PATH_DIR="logs" # Root log dir; col_run.sh appends /${MODEL_NAME}/DATE automatically
SAVE_DIR_BASE="/home/skl/mkx/save_checkpoint" # Root save dir; col_run.sh appends /${MODEL_NAME}/DATE_TIME automatically
SAVE_INTERVAL="" # If not passed, the default is to save a checkpoint every epoch

# Datasets
DATASET_PATH="/home/skl/mkx/data/big_vul/datasets/big_vul_balance"

# Wandb
USE_WANDB=1
WANDB_PROJECT="col_finetune"
WANDB_ENTITY="viobert-skl"
WANDB_RUN_NAME="" # If not passed, the default is to use the model name
# USE_WANDB=0
# WANDB_PROJECT=""
# WANDB_ENTITY=""
# WANDB_RUN_NAME=""

# GPU settings
PLUGIN_NAME="hybrid_parallel"
GPUS="0,1,2,3,4,5,6,7"
TPSIZE=2
PPSIZE=2

# Training schedule
N_EPOCHS=4
LR="0.00002"
MAX_LENGTH=2048

BATCH_SIZE=4
MICROBATCH_SIZE=2
